version: '3.5'
services:
  db_1_master:
    image: hub.c.163.com/library/mysql:5.7
    container_name: "db_1_master"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: bytearch
    #command:
    volumes:
      - ./db_1_master/conf.d/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_1_master/data:/var/lib/mysql
    networks:
        default:
          ipv4_address: 172.30.1.21
  db_1_slave:
    image: hub.c.163.com/library/mysql:5.7
    container_name: "db_1_slave"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: bytearch
    #command:
    depends_on:
      - db_1_master
    volumes:
      - ./db_1_slave/conf.d/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_1_slave/data:/var/lib/mysql
    networks:
        default:
          ipv4_address: 172.30.1.31
  db_2_master:
    image: hub.c.163.com/library/mysql:5.7
    container_name: "db_2_master"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: bytearch
    #command:
    volumes:
      - ./db_2_master/conf.d/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_2_master/data:/var/lib/mysql
    networks:
        default:
          ipv4_address: 172.30.1.22
  db_2_slave:
    image: hub.c.163.com/library/mysql:5.7
    container_name: "db_2_slave"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: bytearch
    #command:
    depends_on:
      - db_2_master
    volumes:
      - ./db_2_slave/conf.d/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_2_slave/data:/var/lib/mysql
    networks:
        default:
          ipv4_address: 172.30.1.32
  db_3_master:
    image: hub.c.163.com/library/mysql:5.7
    container_name: "db_3_master"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: bytearch
    #command:
    volumes:
      - ./db_3_master/conf.d/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_3_master/data:/var/lib/mysql
    networks:
        default:
          ipv4_address: 172.30.1.23
  db_3_slave:
    image: hub.c.163.com/library/mysql:5.7
    container_name: "db_3_slave"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: bytearch
    #command:
    depends_on:
      - db_3_master
    volumes:
      - ./db_3_slave/conf.d/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_3_slave/data:/var/lib/mysql
    networks:
        default:
          ipv4_address: 172.30.1.33
  db_4_master:
    image: hub.c.163.com/library/mysql:5.7
    container_name: "db_4_master"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: bytearch
    #command:
    volumes:
      - ./db_4_master/conf.d/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_4_master/data:/var/lib/mysql
    networks:
        default:
          ipv4_address: 172.30.1.24
  db_4_slave:
    image: hub.c.163.com/library/mysql:5.7
    container_name: "db_4_slave"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: bytearch
    #command:
    depends_on:
      - db_4_master
    volumes:
      - ./db_4_slave/conf.d/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_4_slave/data:/var/lib/mysql
    networks:
        default:
          ipv4_address: 172.30.1.34

networks:
   default:
    external:
      name: app-network