version: "3.5"

services:
  web:
    image: nginx:1.20.1
    restart: always
    hostname: nginx
    container_name: nginx
    volumes:
       - ./conf/conf.d:/etc/nginx/conf.d
       - ./logs:/var/log/nginx
       - ./www:/www
    ports:
      - "8088:80"
    environment:
      - NGINX_PORT=80
    networks:
        default:
          ipv4_address: 172.30.1.11
networks:
   default:
    external:
      name: app-network