version: '3.5'
services:
  nacos:
   image: nacos/nacos-server:v2.0.3
   container_name: nacos_standlone
   hostname: nacos_standlone
   env_file:
      - ./env/nacos-standlone-mysql.env
   volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
   expose:
   - 8848
   restart: always
   networks:
        default:
          ipv4_address: 172.30.1.10
networks:
   default:
    external:
      name: app-network