version: '3.5'
services:
  es:
    image: elasticsearch:6.8.18
    restart: always
    container_name: "elasticsearch"
    hostname: elasticsearch
    ports:
       - 9200:9200
       - 9300:9300
    environment:
      - discovery.type=single-node
    #command:
    
    #volumes:
    networks:
        default:
          ipv4_address: 172.30.1.12
networks:
   default:
    external:
      name: app-network