version: '3.5'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        restart: always
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms2048M -Xmx2048M"
          - http.cors.enabled=true
          - http.cors.allow-origin=*
        ulimits:
          nproc: 65535
          memlock:
            soft: -1
            hard: -1
        #volumes:
      
        ports:
         - 9200:9200
         - 9300:9300
        networks:
          default:
            ipv4_address: 172.30.1.60
    oap:
        image: apache/skywalking-oap-server:8.7.0-es7 
        container_name: oap 
        depends_on:
           - elasticsearch 
        links: 
           - elasticsearch 
        restart: always 
        ports: 
          - 11800:11800
          - 12800:12800
        healthcheck:
          test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 10s
        environment: 
          SW_STORAGE: elasticsearch7 # 指定ES版本 
          SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200 
          SW_HEALTH_CHECKER: default
          SW_TELEMETRY: prometheus
          TZ: Asia/Shanghai
        networks:
         default:
          ipv4_address: 172.30.1.58
    ui:
        image: apache/skywalking-ui:8.7.0 
        container_name: ui 
        depends_on: 
          - oap
        links: 
          - oap 
        restart: always 
        ports: 
          - 8091:8080 
        environment: 
          SW_OAP_ADDRESS: oap:12800 
          TZ: Asia/Shanghai
        networks:
         default:
          ipv4_address: 172.30.1.59
networks:
   default:
    external:
      name: app-network